### ISSUE TITLE
Crash when selecting categories after sorting by alphabet

### ISSUE THREAD

**Issue by piotr25691** [Team-Infinitesimal/Infinitesimal#24]
When you press Ctrl+[any letter] to sort by a letter of the alphabet, then go back to select a song category, OutFox will crash on this theme.

It doesn't seem like OutFox puts any crash logs though, I can't send those.

**Comment by moruzerinho6** [comment]
Where there at least any logs generated? (Those are usually located at the Project OutFox/Logs/log.txt)

**Comment by piotr25691** [comment]
> Were there at least any logs generated? (Those are usually located at the Project OutFox/Logs/log.txt)

Just the normal logs? I'll send them soon. However there was no crash report generated.

**Comment by dj505** [comment]
Alphabet sorting isn't officially supported by the theme and will be replaced once a Lua wheel is implemented

**Comment by piotr25691** [comment]
> Alphabet sorting isn't officially supported by the theme and will be replaced once a Lua wheel is implemented

Could've just disabled it lol
