### ISSUE TITLE
Level channels?

### ISSUE THREAD

**Issue by joannawolthuis** [Team-Infinitesimal/Infinitesimal#25]
Hi there! I was wondering if you were considering adding level channels :)
More specifically - if you were - I would love an option where I can select all songs of for example level 7, but still see the higher level songs as well. I play with friends and we take a lot of time finding songs that have a 7 AND something above 10...
You'd be an angel if you can add a feature like this!

Cheers,
Joanna

**Comment by SheepyChris** [comment]
We're currently working on a new music wheel system over at the dev branch which will allow us to do level sorting and other things as well, when it's done and stable to use we'll be making a new release with the feature soon 🙂
